# Generated by Django 5.1.2 on 2024-10-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='titel',
            new_name='title',
        ),
    ]
