# Generated by Django 5.1.2 on 2024-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='AppItems',
        ),
    ]
