# Generated by Django 5.1.2 on 2024-10-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_rename_apps_appitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppItems',
            new_name='AppItem',
        ),
    ]
