# Generated by Django 5.1.2 on 2024-10-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_rename_appitems_appitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appitem',
            old_name='app_name',
            new_name='appName',
        ),
    ]
