# Generated by Django 5.1.2 on 2024-10-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_rename_app_name_appitem_appname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appitem',
            old_name='appName',
            new_name='name',
        ),
    ]
